@startuml relationships

package Model {
    class Movie <<entity>> {
        - title : String
        - isPresale : boolean
        - showings : ArrayList<Showing>
        + addShowing(st : Showing)
    }

    class Theatre <<entity>> {
        - name : String
        - address : String
        - showings : ArrayList<Showing>
        + addShowing(st : Showing)
    }

    class Showing <<entity>> {
        - time : String
        - movie : Movie
        - theatre : Theatre
        - seat : ArrayList<Seats>
        - ticket : ArrayList<Ticket>
    }

    class Seat <<entity>> {
        - number : int
        - ticket : Ticket
    }

    class Ticket <<entity>> {
        - id : int
        - movie : Movie
        - theatre : Theatre
        - showing : Showing
        - seat : Seat
        - cost : double
        - isCredited : boolean
    }

    class RegisteredUser <<entity>> {
        - emailAddress : String
        - password : String
        - creditCard : String
        - firstName : String
        - lastName : String
        - address : String
        - annualFeeExpiryDate : String
        - tickets : ArrayList<Ticket>
        + addTicket(t : Ticket)
    }

    class DatabaseConnection <<boundary>> {
        - instance : DatabaseConnection
        - connection :  mysqlConnection
        + getInstance()
        + getConnection()
        + query()
    }
}

package Frontend-React {
    class RegisterViewController <<boundary>> {

    }
    class LoginViewController <<boundary>> {

    }
    class AccountViewController <<boundary>> {

    }
    class TicketBuyingViewController <<boundary>> {

    }
    class MovieViewController <<boundary>> {

    }
    class TheatreViewController <<boundary>> {

    }
    class ShowingViewController <<boundary>> {

    }
    class SeatViewController <<boundary>> {

    }
    class PaymentViewController <<boundary>> {

    }
    class ReceiptViewController <<boundary>> {

    }

    class APIContextController {
        ' add getters and setters
        - getters()
        - setters()
    }
}

package Controller-Express {
    class ServerController <<control>> {
        - emailReceipt(ticket : Ticket, emailAddress : String)
        - emailNews(user : RegisteredUser, news : String)
    }

    class userController <<control>> {}
    class userService <<control>> {}

    class seatController <<control>> {}
    class seatService <<control>> {}

    class showingController <<control>> {}
    class showingService <<control>> {}

    class movieController <<control>> {}
    class movieService <<control>> {}

    class theatreController <<control>> {}
    class theatreService <<control>> {}

    class presaleService <<control>> {}
}

TicketBuyingViewController *-- MovieViewController
TicketBuyingViewController *-- TheatreViewController
TicketBuyingViewController *-- ShowingViewController
TicketBuyingViewController *-- SeatViewController
TicketBuyingViewController *-- PaymentViewController
TicketBuyingViewController *-- ReceiptViewController

RegisterViewController --> APIContextController
LoginViewController --> APIContextController
AccountViewController --> APIContextController
TicketBuyingViewController --> APIContextController
MovieViewController --> APIContextController
TheatreViewController --> APIContextController
ShowingViewController --> APIContextController
SeatViewController --> APIContextController
PaymentViewController --> APIContextController
ReceiptViewController --> APIContextController

' start Relationships betweens controllers/services/models
movieController --> movieService
movieService --> Movie
movieService --> showingService

theatreController --> theatreService
theatreService --> Theatre
theatreService --> showingService

seatController --> seatService
seatService --> Seat
seatService --> presaleService
presaleService --> Seat

showingController --> showingService
showingService --> Showing
showingService --> seatService
' --end Relationships betweens controllers/services/models

Movie -- Showing
Theatre -- Showing
Showing *-r- Seat
Ticket o-- Movie
Ticket o-- Theatre
Ticket o-- Showing
Ticket --- Seat
RegisteredUser --> Ticket

package MySQL <<Database>> {
  class Database
}

DatabaseConnection *-- DatabaseConnection
DatabaseConnection -- Database

APIContextController -- ServerController : API communication

@enduml