@startuml relationships

class RegisteredUser <<entity>> {
    - email : String
    - password : String
    - creditCard : String
    - firstName : String
    - lastName : String
    - address : String
    - annualFeeExpiryDate : String
    - tickets : ArrayList<Ticket>
    - ticketRefunds : ArrayList<TicketRefund>
}

class Movie <<entity>> {
    - title : String
}

class Theatre <<entity>> {
    - name : String
}

class ShowTime <<entity>> {
    - time : String
}
class Seat {
    - number : int
    - isOccupied : boolean
}

class Payment <<entity>> {
    - isCompleted : boolean
}

class Ticket <<entity>> {
    - id : int
    - movie : Movie
    - theatre : Theatre
    - time : ShowTime
    - seat : Seat
    - cost : double
    - isCancelled : boolean
}

class TicketRefund <<entity>> {
    - ticketId : int
    - credit : double
    - isRedeemed : boolean
}

class email {}

class RegisterView <<boundary>>
class LoginView <<boundary>>
class AccountView <<boundary>>
class MovieView <<boundary>>
class TheatreView <<boundary>>
class ShowTimeView <<boundary>>
class SeatView <<boundary>>
class PaymentView <<boundary>>
class ReceiptView <<boundary>>

class ServerController <<control>>

@enduml